namespace LafErp.Core;

// Entities generated by the LocalAIFactory generator from the spec-driven modules (data-driven generation).
public class BillOfMaterials : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string ItemCode { get; set; } = string.Empty;
    public decimal Quantity { get; set; }
    public bool IsActive { get; set; }
}

public class WorkOrder : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string BomName { get; set; } = string.Empty;
    public decimal PlannedQty { get; set; }
    public decimal ProducedQty { get; set; }
    public string Status { get; set; } = string.Empty;
}

public class QualityInspection : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string ReferenceType { get; set; } = string.Empty;
    public string Result { get; set; } = string.Empty;
    public DateTime? InspectedOn { get; set; }
}

public class Employee : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string EmployeeCode { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public string Designation { get; set; } = string.Empty;
    public DateTime? DateOfJoining { get; set; }
    public bool IsActive { get; set; }
}

public class SalaryComponent : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string ComponentType { get; set; } = string.Empty;
    public decimal Amount { get; set; }
}

public class PosProfile : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string WarehouseCode { get; set; } = string.Empty;
    public bool AllowDiscount { get; set; }
}

public class WebProduct : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string ItemCode { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public bool Published { get; set; }
}

public class MaintenanceSchedule : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string AssetName { get; set; } = string.Empty;
    public DateTime? NextDue { get; set; }
    public string Frequency { get; set; } = string.Empty;
}

public class CustomFieldDef : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string DocType { get; set; } = string.Empty;
    public string FieldType { get; set; } = string.Empty;
    public bool IsRequired { get; set; }
}

public class NotificationRule : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string Event { get; set; } = string.Empty;
    public string Channel { get; set; } = string.Empty;
    public bool IsEnabled { get; set; }
}

