namespace LafErp.Core;

// Catalog entities generated by the LocalAIFactory generator from a governed local-LLM proposal.
public class CustomerSegment : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal DiscountRate { get; set; }
}

public class PaymentTerm : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public int DaysDue { get; set; }
    public decimal DiscountPercentage { get; set; }
}

public class TaxCode : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public decimal Rate { get; set; }
    public string Description { get; set; } = string.Empty;
}

