// <auto-generated />
using System;
using LocalAIFactory.Core.Enums;
using LocalAIFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalAIFactory.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Project", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsGlobal")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("Projects");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Tags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ModelConfiguration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<ModelProvider>("Provider")
                    .HasColumnType("int");

                b.Property<string>("ModelName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("BaseUrl")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("ApiKeyEncrypted")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Temperature")
                    .HasColumnType("float");

                b.Property<int>("MaxTokens")
                    .HasColumnType("int");

                b.Property<int>("ContextWindowHint")
                    .HasColumnType("int");

                b.Property<string>("EmbeddingModel")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit");

                b.Property<bool>("IsDefault")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("ModelConfigurations");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.PromptTemplate", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Kind")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDefault")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("PromptTemplates");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.SystemSetting", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Key")
                    .IsUnique();

                b.ToTable("SystemSettings");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AuditLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("EntityName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("EntityId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Details")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.TaskProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<TaskType>("TaskType")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int?>("PrimaryModelId")
                    .HasColumnType("int");

                b.Property<bool>("ValidationEnabled")
                    .HasColumnType("bit");

                b.Property<int?>("ValidationModelId")
                    .HasColumnType("int");

                b.Property<bool>("ComparisonEnabled")
                    .HasColumnType("bit");

                b.Property<int?>("ComparisonModelId")
                    .HasColumnType("int");

                b.Property<bool>("UseKnowledgeBase")
                    .HasColumnType("bit");

                b.Property<bool>("UseProjectMemory")
                    .HasColumnType("bit");

                b.Property<bool>("UseKnowledgeGraph")
                    .HasColumnType("bit");

                b.Property<double>("Temperature")
                    .HasColumnType("float");

                b.Property<int>("MaxTokens")
                    .HasColumnType("int");

                b.Property<int>("ContextWindowHint")
                    .HasColumnType("int");

                b.Property<bool>("LocalOnly")
                    .HasColumnType("bit");

                b.Property<bool>("RequireApprovalBeforeCloudUse")
                    .HasColumnType("bit");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("TaskType")
                    .IsUnique();

                b.HasIndex("PrimaryModelId");

                b.HasIndex("ValidationModelId");

                b.HasIndex("ComparisonModelId");

                b.ToTable("TaskProfiles");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectSource", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Path")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<ProjectSourceKind>("Kind")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("ProjectSources");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<SourceType>("SourceType")
                    .HasColumnType("int");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<double>("Confidence")
                    .HasColumnType("float");

                b.Property<bool>("IsApproved")
                    .HasColumnType("bit");

                b.Property<bool>("IsDeprecated")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "Status");

                b.HasIndex("IsApproved");

                b.ToTable("KnowledgeItems");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatSession", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("ModelConfigurationId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.HasIndex("ModelConfigurationId");

                b.ToTable("ChatSessions");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippet", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Language")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Framework")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Explanation")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SourceReference")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsReusable")
                    .HasColumnType("bit");

                b.Property<DateTime>("ApprovedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "IsReusable");

                b.ToTable("ApprovedCodeSnippets");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRule", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<BusinessRuleStatus>("Status")
                    .HasColumnType("int");

                b.Property<bool>("IsApproved")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ApprovedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "IsApproved");

                b.ToTable("BusinessRules");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AgentTask", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("ChatSessionId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("Goal")
                    .HasColumnType("nvarchar(max)");

                b.Property<AgentTaskStatus>("Status")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("CompletedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("AgentTasks");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedConversation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<ConversationSource>("Source")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("RawJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MessageCount")
                    .HasColumnType("int");

                b.Property<ImportStatus>("Status")
                    .HasColumnType("int");

                b.Property<int?>("KnowledgeItemId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("ImportedConversations");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.IngestionJob", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("ExtractedRoot")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<IngestionJobStatus>("Status")
                    .HasColumnType("int");

                b.Property<IngestionPhase>("Phase")
                    .HasColumnType("int");

                b.Property<int>("TotalFiles")
                    .HasColumnType("int");

                b.Property<int>("ProcessedFiles")
                    .HasColumnType("int");

                b.Property<int>("SkippedFiles")
                    .HasColumnType("int");

                b.Property<int>("ChunkCount")
                    .HasColumnType("int");

                b.Property<int>("EmbeddedCount")
                    .HasColumnType("int");

                b.Property<string>("Error")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("StartedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("CompletedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("IngestionJobs");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ProjectId")
                    .HasColumnType("int");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<string>("Summary")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("StructuredJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("GeneratedByModelConfigurationId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("ProjectProfiles");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<EntityType>("EntityType")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<int?>("SourceKnowledgeItemId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "Name");

                b.ToTable("KnowledgeEntities");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.PromptRun", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("ChatSessionId")
                    .HasColumnType("int");

                b.Property<TaskType>("TaskType")
                    .HasColumnType("int");

                b.Property<string>("UserPrompt")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RetrievedContextJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("PromptRuns");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ExtractedCodeBlock", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("ImportedConversationId")
                    .HasColumnType("int");

                b.Property<int?>("SourceKnowledgeItemId")
                    .HasColumnType("int");

                b.Property<string>("Language")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Content")
                    .HasColumnType("nvarchar(max)");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<int?>("PromotedToApprovedCodeSnippetId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("ExtractedCodeBlocks");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedFile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("IngestionJobId")
                    .HasColumnType("int");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(400)
                    .HasColumnType("nvarchar(400)");

                b.Property<string>("RelativePath")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Extension")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("ContentType")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<FileClass>("FileClass")
                    .HasColumnType("int");

                b.Property<long>("SizeBytes")
                    .HasColumnType("bigint");

                b.Property<string>("Sha256")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<string>("RawText")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("StoredPath")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Skipped")
                    .HasColumnType("bit");

                b.Property<string>("SkipReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<ImportStatus>("Status")
                    .HasColumnType("int");

                b.Property<int?>("KnowledgeItemId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.HasIndex("IngestionJobId");

                b.ToTable("ImportedFiles");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeChunk", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("KnowledgeItemId")
                    .HasColumnType("int");

                b.Property<int>("ChunkIndex")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TokenCount")
                    .HasColumnType("int");

                b.Property<string>("VectorId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EmbeddingModel")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("KnowledgeItemId");

                b.ToTable("KnowledgeChunks");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItemTag", b =>
            {
                b.Property<int>("KnowledgeItemId")
                    .HasColumnType("int");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.HasKey("KnowledgeItemId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("KnowledgeItemTags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippetTag", b =>
            {
                b.Property<int>("ApprovedCodeSnippetId")
                    .HasColumnType("int");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.HasKey("ApprovedCodeSnippetId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("ApprovedCodeSnippetTags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRuleTag", b =>
            {
                b.Property<int>("BusinessRuleId")
                    .HasColumnType("int");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.HasKey("BusinessRuleId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("BusinessRuleTags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ChatSessionId")
                    .HasColumnType("int");

                b.Property<ChatRole>("Role")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TokenCount")
                    .HasColumnType("int");

                b.Property<string>("RetrievedContextJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ModelConfigurationId")
                    .HasColumnType("int");

                b.Property<int?>("ModelOutputId")
                    .HasColumnType("int");

                b.Property<MessageRating>("Rating")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ChatSessionId");

                b.ToTable("ChatMessages");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AgentStep", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("AgentTaskId")
                    .HasColumnType("int");

                b.Property<int>("StepIndex")
                    .HasColumnType("int");

                b.Property<AgentStepKind>("Kind")
                    .HasColumnType("int");

                b.Property<string>("Input")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Output")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("AgentTaskId");

                b.ToTable("AgentSteps");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedConversationMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ImportedConversationId")
                    .HasColumnType("int");

                b.Property<ChatRole>("Role")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("OrderIndex")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ImportedConversationId");

                b.ToTable("ImportedConversationMessages");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectProfileSection", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ProjectProfileId")
                    .HasColumnType("int");

                b.Property<string>("SectionKey")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Content")
                    .HasColumnType("nvarchar(max)");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<int>("OrderIndex")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ProjectProfileId");

                b.ToTable("ProjectProfileSections");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeRelationship", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<int>("FromEntityId")
                    .HasColumnType("int");

                b.Property<int>("ToEntityId")
                    .HasColumnType("int");

                b.Property<RelationType>("RelationType")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<KnowledgeStatus>("Status")
                    .HasColumnType("int");

                b.Property<double>("Confidence")
                    .HasColumnType("float");

                b.Property<int?>("SourceKnowledgeItemId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.HasIndex("FromEntityId");

                b.HasIndex("ToEntityId");

                b.ToTable("KnowledgeRelationships");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ModelOutput", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("PromptRunId")
                    .HasColumnType("int");

                b.Property<int?>("ModelConfigurationId")
                    .HasColumnType("int");

                b.Property<ModelOutputKind>("Kind")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PromptTokens")
                    .HasColumnType("int");

                b.Property<int?>("CompletionTokens")
                    .HasColumnType("int");

                b.Property<int?>("LatencyMs")
                    .HasColumnType("int");

                b.Property<bool>("IsApproved")
                    .HasColumnType("bit");

                b.Property<MessageRating>("Rating")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PromptRunId");

                b.HasIndex("ModelConfigurationId");

                b.ToTable("ModelOutputs");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Workspace", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("ProjectId")
                    .HasColumnType("int");

                b.Property<int?>("IngestionJobId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RootPath")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("Version")
                    .HasColumnType("int");

                b.Property<WorkspaceStatus>("Status")
                    .HasColumnType("int");

                b.Property<bool>("IsOriginalImport")
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("Workspaces");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceSnapshot", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("WorkspaceId")
                    .HasColumnType("int");

                b.Property<int?>("ProjectId")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("FileCount")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("WorkspaceId");

                b.ToTable("WorkspaceSnapshots");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceChange", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("WorkspaceId")
                    .HasColumnType("int");

                b.Property<int?>("WorkspaceSnapshotId")
                    .HasColumnType("int");

                b.Property<string>("RelativePath")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("PreviousContent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NewContent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Reason")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Prompt")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ModelUsed")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<WorkspaceChangeStatus>("Status")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("WorkspaceId");

                b.ToTable("WorkspaceChanges");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceFile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("WorkspaceId")
                    .HasColumnType("int");

                b.Property<string>("RelativePath")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Hash")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<FileClass>("FileType")
                    .HasColumnType("int");

                b.Property<long>("SizeBytes")
                    .HasColumnType("bigint");

                b.Property<DateTime?>("LastModifiedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("WorkspaceId");

                b.ToTable("WorkspaceFiles");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.TaskProfile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ModelConfiguration", "PrimaryModel")
                    .WithMany()
                    .HasForeignKey("PrimaryModelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("PrimaryModel");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.TaskProfile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ModelConfiguration", "ValidationModel")
                    .WithMany()
                    .HasForeignKey("ValidationModelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ValidationModel");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.TaskProfile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ModelConfiguration", "ComparisonModel")
                    .WithMany()
                    .HasForeignKey("ComparisonModelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ComparisonModel");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectSource", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany("Sources")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItem", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatSession", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatSession", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ModelConfiguration", "ModelConfiguration")
                    .WithMany()
                    .HasForeignKey("ModelConfigurationId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ModelConfiguration");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippet", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRule", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AgentTask", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedConversation", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.IngestionJob", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectProfile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeEntity", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.PromptRun", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ExtractedCodeBlock", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedFile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedFile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.IngestionJob", "IngestionJob")
                    .WithMany()
                    .HasForeignKey("IngestionJobId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("IngestionJob");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeChunk", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.KnowledgeItem", "KnowledgeItem")
                    .WithMany("Chunks")
                    .HasForeignKey("KnowledgeItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("KnowledgeItem");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItemTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.KnowledgeItem", "KnowledgeItem")
                    .WithMany("Tags")
                    .HasForeignKey("KnowledgeItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("KnowledgeItem");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItemTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Tag");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippetTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ApprovedCodeSnippet", "ApprovedCodeSnippet")
                    .WithMany("Tags")
                    .HasForeignKey("ApprovedCodeSnippetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ApprovedCodeSnippet");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippetTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Tag");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRuleTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.BusinessRule", "BusinessRule")
                    .WithMany("Tags")
                    .HasForeignKey("BusinessRuleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BusinessRule");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRuleTag", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Tag");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatMessage", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ChatSession", "ChatSession")
                    .WithMany("Messages")
                    .HasForeignKey("ChatSessionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChatSession");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AgentStep", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.AgentTask", "AgentTask")
                    .WithMany("Steps")
                    .HasForeignKey("AgentTaskId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("AgentTask");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedConversationMessage", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ImportedConversation", "ImportedConversation")
                    .WithMany("Messages")
                    .HasForeignKey("ImportedConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ImportedConversation");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectProfileSection", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ProjectProfile", "ProjectProfile")
                    .WithMany("Sections")
                    .HasForeignKey("ProjectProfileId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ProjectProfile");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeRelationship", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeRelationship", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.KnowledgeEntity", "FromEntity")
                    .WithMany()
                    .HasForeignKey("FromEntityId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("FromEntity");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeRelationship", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.KnowledgeEntity", "ToEntity")
                    .WithMany()
                    .HasForeignKey("ToEntityId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ToEntity");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ModelOutput", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.PromptRun", "PromptRun")
                    .WithMany("Outputs")
                    .HasForeignKey("PromptRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("PromptRun");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ModelOutput", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.ModelConfiguration", "ModelConfiguration")
                    .WithMany()
                    .HasForeignKey("ModelConfigurationId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ModelConfiguration");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Workspace", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceSnapshot", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Workspace", "Workspace")
                    .WithMany("Snapshots")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Workspace");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceChange", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Workspace", "Workspace")
                    .WithMany("Changes")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Workspace");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.WorkspaceFile", b =>
            {
                b.HasOne("LocalAIFactory.Core.Entities.Workspace", "Workspace")
                    .WithMany("Files")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Workspace");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Project", b =>
            {
                b.Navigation("Sources");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.KnowledgeItem", b =>
            {
                b.Navigation("Chunks");
                b.Navigation("Tags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ApprovedCodeSnippet", b =>
            {
                b.Navigation("Tags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.BusinessRule", b =>
            {
                b.Navigation("Tags");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ChatSession", b =>
            {
                b.Navigation("Messages");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.AgentTask", b =>
            {
                b.Navigation("Steps");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ImportedConversation", b =>
            {
                b.Navigation("Messages");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.ProjectProfile", b =>
            {
                b.Navigation("Sections");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.PromptRun", b =>
            {
                b.Navigation("Outputs");
            });

            modelBuilder.Entity("LocalAIFactory.Core.Entities.Workspace", b =>
            {
                b.Navigation("Changes");
                b.Navigation("Files");
                b.Navigation("Snapshots");
            });

#pragma warning restore 612, 618
        }
    }
}
