namespace LafErp.Core;

// Entities generated by the LocalAIFactory generator from the governed local-LLM catalog proposal.
public class CustomerSegment : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal DiscountRate { get; set; }
}

public class ProductCategory : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public int ParentCategoryId { get; set; }
    public bool IsActive { get; set; }
}

public class EmployeeRole : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public decimal Salary { get; set; }
}

public class MarketingCampaign : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public DateTime StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public decimal Budget { get; set; }
}

public class VendorContract : EntityBase
{
    public string Name { get; set; } = string.Empty;
    public int SupplierId { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime? EndDate { get; set; }
}

